### PR TITLE
Change admin config field DSL to define fields by ID rather than name

### PR DESCRIPTION
**Pull request by mttdffy**
WORKAREA-275

I'll have to update this with the PR for require, but its done so I opened this.

### CODE REVIEW

**Comment by bencrouse** [comment]
Looks good to me.

**Comment by bencrouse** [comment]
So I merged #513, no conflicts here, was there anything else you wanted to check before merging?

**Comment by mttdffy** [comment]
> So I merged #513, no conflicts here, was there anything else you wanted to check before merging?

No. I thought for sure there would be issues. I think I assumed you'd be adding `required: true` to all the existing fields in `00_configuration.rb`. We should do that, no?

**Comment by bencrouse** [comment]
Yeah, I'll update.

**Review by bencrouse — APPROVED** [review]

**Pull request merged**
