### PR TITLE
Only check notablescan in development

### PR DESCRIPTION
**Pull request by mcfearsome**
#31

### CODE REVIEW

**Comment by bencrouse** [comment]
So is the goal with this one to prevent admin db access or to fix the fact that the client we use for the notablescan check doesn't use the same config as the Mongoid default? I ask because this might be a better fix: https://github.com/workarea-commerce/workarea/commit/9d184e7193b844c58a2cf436d9e218eadb8655e2

But only if the goal isn't to prevent admin db access. Maybe I just merge that into this branch and we get both fixes?

**Comment by mcfearsome** [comment]
When I looked at what was being checked, it seemed to me it wasn't required unless you were running tests against a specific environments mongo instance.  Perhaps this is only relevant for our way of doing things, but the staging/production mongo instances will never have tests ran against them and so this fix seemed the simplest course of action.

**Comment by bencrouse** [comment]
Yeah, I'm trying to understand the goal a bit deeper to see if that other commit is actually a better (deeper) fix. But that's dependent on whether we think the app should have access to the admin database at all. If we do think the app should have admin db access, then the other fix would be preferable since then if notablescan got turned on in any non-test env, you'd still get a warning.

**Comment by bencrouse** [comment]
Thanks @mcfearsome !

**Pull request merged**
