### PR TITLE
Add documentation for config.send_transactional_emails

### PR DESCRIPTION
**Pull request by mttdffy**
WORKAREA-317

### CODE REVIEW

**Review by bencrouse — CHANGES_REQUESTED** [review]
Would you add something about how the default value prevents non-admin mail from being sent in non-production environments? That confusion is the main driver for adding this documentation.

**Comment by mttdffy** [comment]
> Would you add something about how the default value prevents non-admin mail from being sent in non-production environments? That confusion is the main driver for adding this documentation.

It doesn't do that? https://github.com/workarea-commerce/workarea/blob/master/core/lib/workarea/configuration.rb#L888

**Comment by bencrouse** [comment]
Oh my bad, this is the wrong config value! This is the one causing the confusion: https://github.com/workarea-commerce/workarea/blob/master/core/lib/workarea/configuration.rb#L927

**Comment by mttdffy** [comment]
> Oh my bad, this is the wrong config value! This is the one causing the confusion: https://github.com/workarea-commerce/workarea/blob/master/core/lib/workarea/configuration.rb#L927

Ah. I will add documentation for that.

**Review by bencrouse — CHANGES_REQUESTED** [review]
Looks good, can you update for `v3.5-stable`?

**Review by bencrouse — APPROVED** [review]

**Pull request merged**
